package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Condition types reported in BuildIdentityStatus.
const (
	// ConditionReady is True when the trust root is complete and usable for
	// admission. A BuildIdentity that is not Ready cannot admit anything.
	ConditionReady = "Ready"
)

// SubjectReference selects the workloads a BuildIdentity governs, within its own
// namespace.
//
// Exactly one of Name or Selector is set. Name is the right answer for a custom
// resource a person applies and names; Selector is the only workable answer for
// Pods, whose names are generated by the ReplicaSet that owns them.
// +kubebuilder:validation:XValidation:rule="has(self.name) != has(self.selector)",message="exactly one of name or selector must be set"
type SubjectReference struct {
	// APIVersion of the governed resource, for example "platform.miportfolio.com/v1"
	// or "v1" for a Pod.
	// +kubebuilder:validation:MinLength=1
	APIVersion string `json:"apiVersion"`

	// Kind of the governed resource, for example "WebApp" or "Pod".
	// +kubebuilder:validation:MinLength=1
	Kind string `json:"kind"`

	// Name of a single governed resource.
	// +kubebuilder:validation:MinLength=1
	// +optional
	Name string `json:"name,omitempty"`

	// Selector matches governed resources by label.
	// +optional
	Selector *metav1.LabelSelector `json:"selector,omitempty"`
}

// BuildProvenance is what the images of a governed workload must prove.
//
// Every field here is compared against a *verified* attestation. Nothing is
// taken from the workload itself, which is the entire point of the type.
type BuildProvenance struct {
	// Issuer is the OIDC issuer that signed the build's identity, for example
	// https://token.actions.githubusercontent.com. A signature from any other
	// issuer is refused even if it is otherwise valid.
	// +kubebuilder:validation:Pattern=`^https://`
	Issuer string `json:"issuer"`

	// Builder is the signing identity that must appear in the certificate, which
	// for GitHub Actions is the reusable workflow that performed the build:
	//
	//   https://github.com/OWNER/REPO/.github/workflows/build-sign.yml@refs/heads/main
	//
	// This is the trusted builder. It is not the repository being built, and
	// confusing the two is how "signed by somebody at GitHub" gets mistaken for
	// a supply-chain control.
	// +kubebuilder:validation:Pattern=`^https://`
	Builder string `json:"builder"`

	// SourceRepository is the repository the provenance must name as the source
	// of the build, for example https://github.com/Mampiz/my-service. This is the
	// field that ties an image to one service and refuses an image built by a
	// different, entirely legitimate workflow.
	// +kubebuilder:validation:Pattern=`^https://`
	SourceRepository string `json:"sourceRepository"`

	// WorkflowPath is the path of the calling workflow within SourceRepository,
	// for example .github/workflows/release.yml. Optional: when empty, any
	// workflow in the source repository is accepted.
	// +optional
	WorkflowPath string `json:"workflowPath,omitempty"`

	// WorkflowRef is the git ref the build ran from, for example
	// refs/heads/main. Optional: when empty, any ref of the source repository is
	// accepted. Leaving it empty means a build from any branch is trusted, which
	// is rarely what anybody wants.
	// +optional
	WorkflowRef string `json:"workflowRef,omitempty"`
}

// BuildIdentitySpec defines the trust root for a workload.
type BuildIdentitySpec struct {
	// Subjects selects the workloads this trust root governs. A workload is
	// governed when it matches any one of them.
	//
	// A list rather than a single subject because one service takes more than
	// one shape in the cluster. A WebApp is admitted, and then the operator
	// creates a Deployment whose pods are admitted separately. Both are the same
	// service and both must prove the same build identity, and splitting that
	// across two BuildIdentity resources would be two places to keep in step.
	// +kubebuilder:validation:MinItems=1
	Subjects []SubjectReference `json:"subjects"`

	// Provenance is what those workloads' images must prove.
	Provenance BuildProvenance `json:"provenance"`

	// ImageRepositories restricts which image repositories this trust root
	// covers, as references without a tag, for example ghcr.io/mampiz/my-service.
	// An image outside the list is refused rather than ignored: a workload that
	// could pull an unrelated image alongside its own would defeat the check.
	// +kubebuilder:validation:MinItems=1
	ImageRepositories []string `json:"imageRepositories"`
}

// BuildIdentityStatus is the observed state of a BuildIdentity.
type BuildIdentityStatus struct {
	// conditions represent the current state of the trust root.
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// observedGeneration is the metadata.generation this status was computed from.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=bid
// +kubebuilder:printcolumn:name="Subject",type=string,JSONPath=`.spec.subject.kind`
// +kubebuilder:printcolumn:name="Source",type=string,JSONPath=`.spec.provenance.sourceRepository`
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=`.status.conditions[?(@.type=="Ready")].status`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// BuildIdentity is the trust root for the images of one workload.
type BuildIdentity struct {
	metav1.TypeMeta `json:",inline"`

	// metadata is a standard object metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// spec defines the trust root
	// +required
	Spec BuildIdentitySpec `json:"spec"`

	// status defines the observed state
	// +optional
	Status BuildIdentityStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BuildIdentityList contains a list of BuildIdentity.
type BuildIdentityList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BuildIdentity `json:"items"`
}
